name: 'Slatify'
description: 'Slack Notification'
author: 'homoluctus'
inputs:
  type:
    description: 'job status (success or failure)'
    required: true
  job_name:
    description: 'job name of workflow (format: markdown)'
    required: true
  icon_emoji:
    description: 'slack icon emoji'
    required: false
    default: 'github'
  channel:
    description: 'slack channel'
    required: false
    default: '#general'
  username:
    description: 'slack username'
    required: false
    default: 'Github Actions'
runs:
  using: 'node12'
  main: 'lib/main.js'