name: 'Slatify'
description: 'Slack Notification for Github Actions'
author: 'homoluctus'
inputs:
  type:
    description: 'job status (success or failure)'
    required: true
  job_name:
    description: 'job name of workflow (format: markdown)'
    required: true
  mention:
    description: 'slack mention'
    required: false
  mention_if:
    description: 'the condition to mention'
    required: false
  username:
    description: 'slack username'
    required: false
  icon_emoji:
    description: 'slack icon emoji'
    required: false
  channel:
    description: 'slack channel'
    required: false
  url:
    description: 'slack incoming webhook url'
    required: false
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'bell'
  color: 'green'