on:
  pull_request:
    - master

  push:
    - test

name: Check if GitHub Actions works properly

jobs:
  check:
    name: Check action
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master

      - name: Slack Notification
        uses: homoluctus/slatify@releases/v1
        if: always()
        with:
          type: ${{ job.status }}
          job_name: ':robot_face: *Check action*'
          url: ${{ secrets.SLACK_WEBHOOK }}